# Generated by Django 3.2.14 on 2022-07-17 16:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='blog_app/category/images')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='blog_app/post/images')),
                ('comment', models.CharField(max_length=1000)),
                ('tags', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('related_cat', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_post', to='blog_app.category')),
            ],
        ),
    ]
